### ISSUE TITLE
Tracking issue for decoding of ETF

### ISSUE THREAD

**Issue by rhbvkleef** [rhbvkleef/rust-eterm#7]
* [ ] Design decoding architecture: #6 
* [ ] [`DIST_HDR_NORMAL`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#distribution-header) (68)
* [ ] [`DIST_HDR_FRAG_START`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#distribution-header) (69)
* [ ] [`DIST_HDR_FRAG_CONT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#distribution-header) (70)
* [ ] `DIST_HDR_COMPRESSED` (80)
* [ ] [`ATOM_CACHE_REF`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#atom_cache_ref) (82)
* [ ] [`SMALL_INTEGER_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#small_integer_ext) (97)
* [ ] [`INTEGER_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#integer_ext) (98)
* [ ] [`FLOAT_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#float_ext) (99)
* [ ] [`PORT_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#port_ext) (102)
* [ ] [`NEW_PORT_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#new_port_ext) (89)
* [ ] [`PID_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#pid_ext) (103)
* [ ] [`NEW_PID_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#new_pid_ext) (88)
* [ ] [`SMALL_TUPLE_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#small_tuple_ext) (104)
* [ ] [`LARGE_TUPLE_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#large_tuple_ext) (105)
* [ ] [`MAP_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#map_ext) (116)
* [ ] [`NIL_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#nil_ext) (106)
* [ ] [`STRING_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#string_ext) (107)
* [ ] [`LIST_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#list_ext) (108)
* [ ] [`BINARY_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#binary_ext) (109)
* [ ] [`SMALL_BIG_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#small_big_ext) (110)
* [ ] [`LARGE_BIG_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#large_big_ext) (111)
* [ ] [`REFERENCE_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#reference_ext--deprecated-) (101)
* [ ] [`NEW_REFERENCE_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#new_reference_ext) (114)
* [ ] [`NEWER_REFERENCE_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#newer_reference_ext) (90)
* [ ] [`FUN_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#fun_ext) (117)
* [ ] [`NEW_FUN_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#new_fun_ext) (112)
* [ ] [`EXPORT_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#export_ext) (113)
* [ ] [`BIT_BINARY_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#bit_binary_ext) (77)
* [ ] [`NEW_FLOAT_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#new_float_ext) (70)
* [ ] [`ATOM_UTF8_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#atom_utf8_ext) (118)
* [ ] [`SMALL_ATOM_UTF8_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#small_atom_utf8_ext) (119)
* [ ] [`ATOM_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#atom_ext--deprecated-) (100)
* [ ] [`SMALL_ATOM_EXT`](http://erlang.org/doc/apps/erts/erl_ext_dist.html#small_atom_ext--deprecated-) (115)
